application:
  name: customer-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: false
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show_sql: false

integration:
  product-api:
    endpoint: http://challenge-api.luizalabs.com

feign:
  hystrix:
    enabled: true
  client:
    config:
      product-api:
        readTimeout: 1500
        connectTimeout: 500

security:
  jwt-secret: luizalabs-token
  users:
    - username: user-api
      password: $2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6 #password
      authorities:
        - WRITE_PRIVILEGE
    - username: user-reader
      password: $2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6 #password
      authorities:
        - READ_PRIVILEGE
